[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://semiramisu.github.io"
    sitemapPath = "/sitemap.xml"
    providers = ["google", "bing"]